### ISSUE TITLE
Overlay issue in the Theme Toolbar.

### ISSUE THREAD

**Issue by LarveyOfficial** [TotalChris/ProjectVoyager#10]
When opening and closing the toolbar, the past window is still shown temporarily, this is also an issue when switching from matte to transparent.

Video: https://drive.google.com/file/d/1rz-JVCzZ7ZP61pbs-b4_GJbfnz_BK2Oq/view?usp=sharing

**Comment by LarveyOfficial** [comment]
when scrolling up and down it gives it a screen burn-in effect making it look like the text is overlaying the old text for a slight moment

**Comment by TotalChris** [comment]
This is probably issues with transparent drawing in the electron window. I'm probably going to remove transparency once I can find a consistent blur-behind effect because the implementation seems broken across Linux platforms.

**Comment by TotalChris** [comment]
See if the latest commit [here](https://github.com/TotalChris/ProjectVoyager/commit/569eae3a8160646eee00806dde89885eba7f84bd) fixes the issues in question. Thanks for the feedback. If you want to help wit transparency or blur-behind you can make a pull request at any time.

**Comment by LarveyOfficial** [comment]
Fixed issue #10 :D
