### ISSUE TITLE
Past Directory Can be seen in New directory

### ISSUE THREAD

**Issue by LarveyOfficial** [TotalChris/ProjectVoyager#11]
When Opening a new directory you can still see the files in the last directory, Looks like a screen burn in effect.

Video: https://drive.google.com/file/d/1foaUfyILU_k4lw0TJR1QE72G7aLPMG8Y/view?usp=sharing

**Comment by TotalChris** [comment]
This is probably issues with transparent drawing in the electron window. I'm probably going to remove transparency once I can find a consistent blur-behind effect because the implementation seems broken across Linux platforms.

**Comment by TotalChris** [comment]
See if the latest commit [here](https://github.com/TotalChris/ProjectVoyager/commit/569eae3a8160646eee00806dde89885eba7f84bd) fixes the issues in question. Thanks for the feedback. If you want to help wit transparency or blur-behind you can make a pull request at any time.

**Comment by LarveyOfficial** [comment]
Fixed issue #11
