### ISSUE TITLE
Right Click

### ISSUE THREAD

**Issue by LarveyOfficial** [TotalChris/ProjectVoyager#17]
When Right-clicking on a file on the bottom of the directory, the right-click menu goes outside of the application.

https://drive.google.com/file/d/1p5iskSEsno_otFFp-3F2NFdwV0ws3iQH/view?usp=sharing

**Comment by TotalChris** [comment]
Added to agenda

**Comment by TotalChris** [comment]
Fixed issue. Commit will be pushed soon.
