### ISSUE TITLE
Clicking outside of Voyager

### ISSUE THREAD

**Issue by LarveyOfficial** [TotalChris/ProjectVoyager#18]
When Clicking outside of Voyager with the Right Click menu open. It dosesn't close the Right-Click menu.

**Comment by TotalChris** [comment]
Added to agenda

**Comment by TotalChris** [comment]
@LarveyOfficial if you want, you can add an event listener that fires when the window loses focus. Use it to hide the context menu. Voyager.js is where the listener should be added. Just want to see how you'd do with something other than a shell script. 😂

**Comment by TotalChris** [comment]
Fixed it myself
