### ISSUE TITLE
Wont Start on MacOS

### ISSUE THREAD

**Issue by LarveyOfficial** [TotalChris/ProjectVoyager#19]
Voyager@1.0.0 start /Users/larvey/ProjectVoyager
> electron .

sh: electron: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! Voyager@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the Voyager@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/larvey/.npm/_logs/2019-04-15T18_51_40_158Z-debug.log

**Comment by LarveyOfficial** [comment]
And Yes electron is installed.

**Comment by TotalChris** [comment]
Delete the node_modules folder and run npm i again. You might also want to check if the integrity of the files is ok
